import { EXERCISES, type Exercise } from "./data";

export type Movement =
  | "Squat"
  | "Hinge"
  | "Lunge"
  | "Push"
  | "Pull"
  | "Isolation"
  | "Core"
  | "Rotation"
  | "Cardio"
  | "Plyometric"
  | "Carry"
  | "Olympic"
  | "Mobility";

export type LibraryExercise = Exercise & {
  movement: Movement;
  sport: string;
  muscles: string[];
  sets: string;
  reps: string;
  rest: number;
};

/** Metadata that enriches the six core workout exercises (ids e1-e18). */
const CORE_META: Record<
  string,
  { movement: Movement; muscles: string[]; sets: string; reps: string; rest: number }
> = {
  e1: { movement: "Squat", muscles: ["Quads", "Glutes", "Core"], sets: "3", reps: "10", rest: 60 },
  e2: { movement: "Push", muscles: ["Chest", "Triceps"], sets: "3", reps: "8-12", rest: 60 },
  e3: { movement: "Pull", muscles: ["Lats", "Mid back"], sets: "3", reps: "10 / side", rest: 60 },
  e4: { movement: "Hinge", muscles: ["Hamstrings", "Glutes"], sets: "4", reps: "8", rest: 90 },
  e5: { movement: "Push", muscles: ["Shoulders", "Triceps"], sets: "3", reps: "8", rest: 90 },
  e6: { movement: "Core", muscles: ["Deep core"], sets: "3", reps: "40 sec", rest: 45 },
  e7: { movement: "Hinge", muscles: ["Glutes", "Hamstrings", "Back"], sets: "4", reps: "15", rest: 45 },
  e8: { movement: "Lunge", muscles: ["Quads", "Glutes"], sets: "3", reps: "10 / side", rest: 75 },
  e9: { movement: "Pull", muscles: ["Lats", "Biceps"], sets: "4", reps: "10", rest: 75 },
  e10: { movement: "Push", muscles: ["Chest", "Triceps"], sets: "4", reps: "6-8", rest: 120 },
  e11: { movement: "Cardio", muscles: ["Core", "Heart"], sets: "4", reps: "40 sec", rest: 30 },
  e12: { movement: "Cardio", muscles: ["Full body", "Heart"], sets: "4", reps: "30 sec", rest: 30 },
  e13: { movement: "Isolation", muscles: ["Rear delts"], sets: "3", reps: "15", rest: 45 },
  e14: { movement: "Core", muscles: ["Abs"], sets: "3", reps: "10", rest: 50 },
  e15: { movement: "Cardio", muscles: ["Full body", "Heart"], sets: "6", reps: "500 m", rest: 60 },
  e16: { movement: "Lunge", muscles: ["Quads", "Glutes"], sets: "3", reps: "20 steps", rest: 60 },
  e17: { movement: "Push", muscles: ["Upper chest", "Triceps"], sets: "3", reps: "10", rest: 75 },
  e18: { movement: "Core", muscles: ["Deep core", "Glutes"], sets: "3", reps: "8 / side", rest: 45 },
};

const CORE_LIBRARY: LibraryExercise[] = EXERCISES.map((e) => {
  const meta = CORE_META[e.id] ?? {
    movement: "Isolation" as Movement,
    muscles: [e.group],
    sets: "3",
    reps: "10",
    rest: 60,
  };
  return { ...e, sport: "Gym", ...meta };
});

const EXTRA_LIBRARY: LibraryExercise[] = [
  { id: "g1", name: "Barbell back squat", group: "Legs", equipment: "Barbell", level: "Intermediate", emoji: "\ud83c\udfcb\ufe0f", movement: "Squat", sport: "Gym", muscles: ["Quads", "Glutes", "Core"], cues: ["Brace your core before you descend", "Keep your whole foot planted", "Drive up smoothly, no bouncing"], sets: "3-4", reps: "6-10", rest: 90 },
  { id: "g2", name: "Front squat", group: "Legs", equipment: "Barbell", level: "Advanced", emoji: "\ud83c\udfcb\ufe0f", movement: "Squat", sport: "Gym", muscles: ["Quads", "Upper back", "Core"], cues: ["Brace your core before you descend", "Keep your whole foot planted", "Drive up smoothly, no bouncing"], sets: "3-4", reps: "6-10", rest: 90 },
  { id: "g3", name: "Hack squat", group: "Legs", equipment: "Machine", level: "Beginner", emoji: "\u2699\ufe0f", movement: "Squat", sport: "Gym", muscles: ["Quads", "Glutes"], cues: ["Brace your core before you descend", "Keep your whole foot planted", "Drive up smoothly, no bouncing"], sets: "3-4", reps: "6-10", rest: 90 },
  { id: "g4", name: "Leg press", group: "Legs", equipment: "Machine", level: "Beginner", emoji: "\u2699\ufe0f", movement: "Squat", sport: "Gym", muscles: ["Quads", "Glutes"], cues: ["Brace your core before you descend", "Keep your whole foot planted", "Drive up smoothly, no bouncing"], sets: "3-4", reps: "6-10", rest: 90 },
  { id: "g5", name: "Box squat", group: "Legs", equipment: "Barbell", level: "Beginner", emoji: "\ud83d\udce6", movement: "Squat", sport: "Gym", muscles: ["Glutes", "Quads"], cues: ["Brace your core before you descend", "Keep your whole foot planted", "Drive up smoothly, no bouncing"], sets: "3-4", reps: "6-10", rest: 90 },
  { id: "g6", name: "Smith machine squat", group: "Legs", equipment: "Machine", level: "Beginner", emoji: "\u2699\ufe0f", movement: "Squat", sport: "Gym", muscles: ["Quads", "Glutes"], cues: ["Brace your core before you descend", "Keep your whole foot planted", "Drive up smoothly, no bouncing"], sets: "3-4", reps: "6-10", rest: 90 },
  { id: "g7", name: "Dumbbell squat", group: "Legs", equipment: "Dumbbell", level: "Beginner", emoji: "\ud83c\udfcb\ufe0f", movement: "Squat", sport: "Gym", muscles: ["Quads", "Glutes"], cues: ["Brace your core before you descend", "Keep your whole foot planted", "Drive up smoothly, no bouncing"], sets: "3-4", reps: "6-10", rest: 90 },
  { id: "g8", name: "Pause squat", group: "Legs", equipment: "Barbell", level: "Advanced", emoji: "\u23f8\ufe0f", movement: "Squat", sport: "Gym", muscles: ["Quads", "Core"], cues: ["Brace your core before you descend", "Keep your whole foot planted", "Drive up smoothly, no bouncing"], sets: "3-4", reps: "6-10", rest: 90 },
  { id: "g9", name: "Sissy squat", group: "Legs", equipment: "Bodyweight", level: "Advanced", emoji: "\ud83e\uddb5", movement: "Squat", sport: "Gym", muscles: ["Quads"], cues: ["Brace your core before you descend", "Keep your whole foot planted", "Drive up smoothly, no bouncing"], sets: "3-4", reps: "6-10", rest: 90 },
  { id: "g10", name: "Wall sit", group: "Legs", equipment: "Bodyweight", level: "Beginner", emoji: "\ud83e\uddf1", movement: "Squat", sport: "Gym", muscles: ["Quads"], cues: ["Brace your core before you descend", "Keep your whole foot planted", "Drive up smoothly, no bouncing"], sets: "3-4", reps: "6-10", rest: 90 },
  { id: "g11", name: "Conventional deadlift", group: "Legs", equipment: "Barbell", level: "Advanced", emoji: "\ud83e\udea8", movement: "Hinge", sport: "Gym", muscles: ["Hamstrings", "Glutes", "Back"], cues: ["Push the hips back, not down", "Keep a long, neutral spine", "Squeeze the glutes at the top"], sets: "3-4", reps: "5-8", rest: 120 },
  { id: "g12", name: "Sumo deadlift", group: "Legs", equipment: "Barbell", level: "Intermediate", emoji: "\ud83e\udea8", movement: "Hinge", sport: "Gym", muscles: ["Glutes", "Quads", "Back"], cues: ["Push the hips back, not down", "Keep a long, neutral spine", "Squeeze the glutes at the top"], sets: "3-4", reps: "5-8", rest: 120 },
  { id: "g13", name: "Trap bar deadlift", group: "Legs", equipment: "Barbell", level: "Beginner", emoji: "\ud83e\udea8", movement: "Hinge", sport: "Gym", muscles: ["Glutes", "Quads", "Back"], cues: ["Push the hips back, not down", "Keep a long, neutral spine", "Squeeze the glutes at the top"], sets: "3-4", reps: "5-8", rest: 120 },
  { id: "g14", name: "Single-leg Romanian deadlift", group: "Legs", equipment: "Dumbbell", level: "Intermediate", emoji: "\ud83e\uddbf", movement: "Hinge", sport: "Gym", muscles: ["Hamstrings", "Glutes"], cues: ["Push the hips back, not down", "Keep a long, neutral spine", "Squeeze the glutes at the top"], sets: "3-4", reps: "5-8", rest: 120 },
  { id: "g15", name: "Hip thrust", group: "Legs", equipment: "Barbell", level: "Beginner", emoji: "\ud83c\udf51", movement: "Hinge", sport: "Gym", muscles: ["Glutes", "Hamstrings"], cues: ["Push the hips back, not down", "Keep a long, neutral spine", "Squeeze the glutes at the top"], sets: "3-4", reps: "5-8", rest: 120 },
  { id: "g16", name: "Glute bridge", group: "Legs", equipment: "Bodyweight", level: "Beginner", emoji: "\ud83c\udf09", movement: "Hinge", sport: "Gym", muscles: ["Glutes"], cues: ["Push the hips back, not down", "Keep a long, neutral spine", "Squeeze the glutes at the top"], sets: "3-4", reps: "5-8", rest: 120 },
  { id: "g17", name: "Back extension", group: "Legs", equipment: "Machine", level: "Beginner", emoji: "\u2699\ufe0f", movement: "Hinge", sport: "Gym", muscles: ["Lower back", "Glutes"], cues: ["Push the hips back, not down", "Keep a long, neutral spine", "Squeeze the glutes at the top"], sets: "3-4", reps: "5-8", rest: 120 },
  { id: "g18", name: "Good morning", group: "Legs", equipment: "Barbell", level: "Advanced", emoji: "\ud83d\ude47", movement: "Hinge", sport: "Gym", muscles: ["Hamstrings", "Lower back"], cues: ["Push the hips back, not down", "Keep a long, neutral spine", "Squeeze the glutes at the top"], sets: "3-4", reps: "5-8", rest: 120 },
  { id: "g19", name: "Cable pull-through", group: "Legs", equipment: "Cable", level: "Beginner", emoji: "\ud83e\udea2", movement: "Hinge", sport: "Gym", muscles: ["Glutes", "Hamstrings"], cues: ["Push the hips back, not down", "Keep a long, neutral spine", "Squeeze the glutes at the top"], sets: "3-4", reps: "5-8", rest: 120 },
  { id: "g20", name: "Kettlebell deadlift", group: "Legs", equipment: "Kettlebell", level: "Beginner", emoji: "\ud83d\udd14", movement: "Hinge", sport: "Gym", muscles: ["Glutes", "Hamstrings"], cues: ["Push the hips back, not down", "Keep a long, neutral spine", "Squeeze the glutes at the top"], sets: "3-4", reps: "5-8", rest: 120 },
  { id: "g21", name: "Reverse lunge", group: "Legs", equipment: "Dumbbell", level: "Beginner", emoji: "\ud83d\udeb6", movement: "Lunge", sport: "Gym", muscles: ["Glutes", "Quads"], cues: ["Upright torso, proud chest", "Front knee tracks over the toes", "Push the floor away to stand"], sets: "3", reps: "8-12 / side", rest: 75 },
  { id: "g22", name: "Curtsy lunge", group: "Legs", equipment: "Dumbbell", level: "Intermediate", emoji: "\ud83d\udc83", movement: "Lunge", sport: "Gym", muscles: ["Glutes"], cues: ["Upright torso, proud chest", "Front knee tracks over the toes", "Push the floor away to stand"], sets: "3", reps: "8-12 / side", rest: 75 },
  { id: "g23", name: "Step-up", group: "Legs", equipment: "Dumbbell", level: "Beginner", emoji: "\ud83e\ude9c", movement: "Lunge", sport: "Gym", muscles: ["Quads", "Glutes"], cues: ["Upright torso, proud chest", "Front knee tracks over the toes", "Push the floor away to stand"], sets: "3", reps: "8-12 / side", rest: 75 },
  { id: "g24", name: "Deficit reverse lunge", group: "Legs", equipment: "Dumbbell", level: "Advanced", emoji: "\ud83e\uddbf", movement: "Lunge", sport: "Gym", muscles: ["Glutes", "Quads"], cues: ["Upright torso, proud chest", "Front knee tracks over the toes", "Push the floor away to stand"], sets: "3", reps: "8-12 / side", rest: 75 },
  { id: "g25", name: "Cossack squat", group: "Legs", equipment: "Bodyweight", level: "Intermediate", emoji: "\ud83d\udd7a", movement: "Mobility", sport: "Gym", muscles: ["Adductors", "Quads"], cues: ["Ease into the range, never force", "Breathe out to sink deeper", "Hold 30-45 seconds per side"], sets: "2", reps: "30-45 sec", rest: 30 },
  { id: "g26", name: "Leg extension", group: "Legs", equipment: "Machine", level: "Beginner", emoji: "\u2699\ufe0f", movement: "Isolation", sport: "Gym", muscles: ["Quads"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g27", name: "Lying leg curl", group: "Legs", equipment: "Machine", level: "Beginner", emoji: "\u2699\ufe0f", movement: "Isolation", sport: "Gym", muscles: ["Hamstrings"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g28", name: "Seated leg curl", group: "Legs", equipment: "Machine", level: "Beginner", emoji: "\u2699\ufe0f", movement: "Isolation", sport: "Gym", muscles: ["Hamstrings"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g29", name: "Standing calf raise", group: "Legs", equipment: "Machine", level: "Beginner", emoji: "\ud83e\uddb6", movement: "Isolation", sport: "Gym", muscles: ["Calves"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g30", name: "Seated calf raise", group: "Legs", equipment: "Machine", level: "Beginner", emoji: "\ud83e\uddb6", movement: "Isolation", sport: "Gym", muscles: ["Calves"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g31", name: "Hip abduction machine", group: "Legs", equipment: "Machine", level: "Beginner", emoji: "\u2699\ufe0f", movement: "Isolation", sport: "Gym", muscles: ["Glutes"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g32", name: "Adductor machine", group: "Legs", equipment: "Machine", level: "Beginner", emoji: "\u2699\ufe0f", movement: "Isolation", sport: "Gym", muscles: ["Adductors"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g33", name: "Incline barbell bench press", group: "Chest", equipment: "Barbell", level: "Intermediate", emoji: "\ud83d\udcd0", movement: "Push", sport: "Gym", muscles: ["Upper chest", "Shoulders", "Triceps"], cues: ["Set the shoulder blades first", "Elbows tucked around 45\u00b0", "Control the lowering phase"], sets: "3-4", reps: "6-12", rest: 90 },
  { id: "g34", name: "Decline bench press", group: "Chest", equipment: "Barbell", level: "Intermediate", emoji: "\ud83d\udcc9", movement: "Push", sport: "Gym", muscles: ["Lower chest", "Triceps"], cues: ["Set the shoulder blades first", "Elbows tucked around 45\u00b0", "Control the lowering phase"], sets: "3-4", reps: "6-12", rest: 90 },
  { id: "g35", name: "Close-grip bench press", group: "Chest", equipment: "Barbell", level: "Intermediate", emoji: "\ud83e\udd0f", movement: "Push", sport: "Gym", muscles: ["Triceps", "Chest"], cues: ["Set the shoulder blades first", "Elbows tucked around 45\u00b0", "Control the lowering phase"], sets: "3-4", reps: "6-12", rest: 90 },
  { id: "g36", name: "Dumbbell bench press", group: "Chest", equipment: "Dumbbell", level: "Beginner", emoji: "\ud83d\udecf\ufe0f", movement: "Push", sport: "Gym", muscles: ["Chest", "Triceps"], cues: ["Set the shoulder blades first", "Elbows tucked around 45\u00b0", "Control the lowering phase"], sets: "3-4", reps: "6-12", rest: 90 },
  { id: "g37", name: "Machine chest press", group: "Chest", equipment: "Machine", level: "Beginner", emoji: "\u2699\ufe0f", movement: "Push", sport: "Gym", muscles: ["Chest", "Triceps"], cues: ["Set the shoulder blades first", "Elbows tucked around 45\u00b0", "Control the lowering phase"], sets: "3-4", reps: "6-12", rest: 90 },
  { id: "g38", name: "Cable fly", group: "Chest", equipment: "Cable", level: "Beginner", emoji: "\ud83d\udd4a\ufe0f", movement: "Isolation", sport: "Gym", muscles: ["Chest"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g39", name: "Pec deck", group: "Chest", equipment: "Machine", level: "Beginner", emoji: "\u2699\ufe0f", movement: "Isolation", sport: "Gym", muscles: ["Chest"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g40", name: "Dumbbell fly", group: "Chest", equipment: "Dumbbell", level: "Intermediate", emoji: "\ud83d\udd4a\ufe0f", movement: "Isolation", sport: "Gym", muscles: ["Chest"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g41", name: "Chest dip", group: "Chest", equipment: "Bodyweight", level: "Intermediate", emoji: "\ud83e\ude91", movement: "Push", sport: "Gym", muscles: ["Lower chest", "Triceps"], cues: ["Set the shoulder blades first", "Elbows tucked around 45\u00b0", "Control the lowering phase"], sets: "3-4", reps: "6-12", rest: 90 },
  { id: "g42", name: "Deficit push-up", group: "Chest", equipment: "Bodyweight", level: "Intermediate", emoji: "\ud83d\udcaa", movement: "Push", sport: "Gym", muscles: ["Chest", "Shoulders"], cues: ["Set the shoulder blades first", "Elbows tucked around 45\u00b0", "Control the lowering phase"], sets: "3-4", reps: "6-12", rest: 90 },
  { id: "g43", name: "Incline push-up", group: "Chest", equipment: "Bodyweight", level: "Beginner", emoji: "\ud83d\udcd0", movement: "Push", sport: "Gym", muscles: ["Chest"], cues: ["Set the shoulder blades first", "Elbows tucked around 45\u00b0", "Control the lowering phase"], sets: "3-4", reps: "6-12", rest: 90 },
  { id: "g44", name: "Svend press", group: "Chest", equipment: "Dumbbell", level: "Beginner", emoji: "\ud83e\udd32", movement: "Isolation", sport: "Gym", muscles: ["Chest"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g45", name: "Pull-up", group: "Back", equipment: "Pull-up bar", level: "Intermediate", emoji: "\ud83e\uddd7", movement: "Pull", sport: "Gym", muscles: ["Lats", "Biceps"], cues: ["Lead with the elbows", "Pause briefly at the top", "Lower under control"], sets: "3-4", reps: "8-12", rest: 90 },
  { id: "g46", name: "Chin-up", group: "Back", equipment: "Pull-up bar", level: "Intermediate", emoji: "\ud83e\uddd7", movement: "Pull", sport: "Gym", muscles: ["Lats", "Biceps"], cues: ["Lead with the elbows", "Pause briefly at the top", "Lower under control"], sets: "3-4", reps: "8-12", rest: 90 },
  { id: "g47", name: "Neutral-grip pull-up", group: "Back", equipment: "Pull-up bar", level: "Intermediate", emoji: "\ud83e\uddd7", movement: "Pull", sport: "Gym", muscles: ["Lats", "Biceps"], cues: ["Lead with the elbows", "Pause briefly at the top", "Lower under control"], sets: "3-4", reps: "8-12", rest: 90 },
  { id: "g48", name: "Barbell row", group: "Back", equipment: "Barbell", level: "Intermediate", emoji: "\ud83d\udea3", movement: "Pull", sport: "Gym", muscles: ["Lats", "Mid back"], cues: ["Lead with the elbows", "Pause briefly at the top", "Lower under control"], sets: "3-4", reps: "8-12", rest: 90 },
  { id: "g49", name: "Pendlay row", group: "Back", equipment: "Barbell", level: "Advanced", emoji: "\ud83d\udea3", movement: "Pull", sport: "Gym", muscles: ["Mid back", "Lats"], cues: ["Lead with the elbows", "Pause briefly at the top", "Lower under control"], sets: "3-4", reps: "8-12", rest: 90 },
  { id: "g50", name: "Seated cable row", group: "Back", equipment: "Cable", level: "Beginner", emoji: "\ud83e\udea2", movement: "Pull", sport: "Gym", muscles: ["Mid back", "Lats"], cues: ["Lead with the elbows", "Pause briefly at the top", "Lower under control"], sets: "3-4", reps: "8-12", rest: 90 },
  { id: "g51", name: "Chest-supported row", group: "Back", equipment: "Machine", level: "Beginner", emoji: "\u2699\ufe0f", movement: "Pull", sport: "Gym", muscles: ["Mid back"], cues: ["Lead with the elbows", "Pause briefly at the top", "Lower under control"], sets: "3-4", reps: "8-12", rest: 90 },
  { id: "g52", name: "T-bar row", group: "Back", equipment: "Barbell", level: "Intermediate", emoji: "\ud83d\udea3", movement: "Pull", sport: "Gym", muscles: ["Mid back", "Lats"], cues: ["Lead with the elbows", "Pause briefly at the top", "Lower under control"], sets: "3-4", reps: "8-12", rest: 90 },
  { id: "g53", name: "Single-arm cable row", group: "Back", equipment: "Cable", level: "Beginner", emoji: "\ud83e\udea2", movement: "Pull", sport: "Gym", muscles: ["Lats"], cues: ["Lead with the elbows", "Pause briefly at the top", "Lower under control"], sets: "3-4", reps: "8-12", rest: 90 },
  { id: "g54", name: "Straight-arm pulldown", group: "Back", equipment: "Cable", level: "Beginner", emoji: "\ud83e\udea2", movement: "Isolation", sport: "Gym", muscles: ["Lats"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g55", name: "Wide-grip lat pulldown", group: "Back", equipment: "Machine", level: "Beginner", emoji: "\u2699\ufe0f", movement: "Pull", sport: "Gym", muscles: ["Lats"], cues: ["Lead with the elbows", "Pause briefly at the top", "Lower under control"], sets: "3-4", reps: "8-12", rest: 90 },
  { id: "g56", name: "Inverted row", group: "Back", equipment: "Bodyweight", level: "Beginner", emoji: "\ud83d\udd3b", movement: "Pull", sport: "Gym", muscles: ["Mid back", "Biceps"], cues: ["Lead with the elbows", "Pause briefly at the top", "Lower under control"], sets: "3-4", reps: "8-12", rest: 90 },
  { id: "g57", name: "Shrug", group: "Back", equipment: "Barbell", level: "Beginner", emoji: "\ud83e\udd37", movement: "Isolation", sport: "Gym", muscles: ["Traps"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g58", name: "Rack pull", group: "Back", equipment: "Barbell", level: "Intermediate", emoji: "\ud83e\udea8", movement: "Hinge", sport: "Gym", muscles: ["Back", "Glutes"], cues: ["Push the hips back, not down", "Keep a long, neutral spine", "Squeeze the glutes at the top"], sets: "3-4", reps: "5-8", rest: 120 },
  { id: "g59", name: "Dumbbell pullover", group: "Back", equipment: "Dumbbell", level: "Intermediate", emoji: "\ud83d\udecf\ufe0f", movement: "Isolation", sport: "Gym", muscles: ["Lats", "Chest"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g60", name: "Seated dumbbell shoulder press", group: "Shoulders", equipment: "Dumbbell", level: "Beginner", emoji: "\ud83d\ude4b", movement: "Push", sport: "Gym", muscles: ["Shoulders", "Triceps"], cues: ["Set the shoulder blades first", "Elbows tucked around 45\u00b0", "Control the lowering phase"], sets: "3-4", reps: "6-12", rest: 90 },
  { id: "g61", name: "Arnold press", group: "Shoulders", equipment: "Dumbbell", level: "Intermediate", emoji: "\ud83c\udf00", movement: "Push", sport: "Gym", muscles: ["Shoulders"], cues: ["Set the shoulder blades first", "Elbows tucked around 45\u00b0", "Control the lowering phase"], sets: "3-4", reps: "6-12", rest: 90 },
  { id: "g62", name: "Machine shoulder press", group: "Shoulders", equipment: "Machine", level: "Beginner", emoji: "\u2699\ufe0f", movement: "Push", sport: "Gym", muscles: ["Shoulders"], cues: ["Set the shoulder blades first", "Elbows tucked around 45\u00b0", "Control the lowering phase"], sets: "3-4", reps: "6-12", rest: 90 },
  { id: "g63", name: "Push press", group: "Shoulders", equipment: "Barbell", level: "Advanced", emoji: "\ud83d\ude80", movement: "Push", sport: "Gym", muscles: ["Shoulders", "Legs"], cues: ["Set the shoulder blades first", "Elbows tucked around 45\u00b0", "Control the lowering phase"], sets: "3-4", reps: "6-12", rest: 90 },
  { id: "g64", name: "Lateral raise", group: "Shoulders", equipment: "Dumbbell", level: "Beginner", emoji: "\ud83e\udd85", movement: "Isolation", sport: "Gym", muscles: ["Side delts"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g65", name: "Cable lateral raise", group: "Shoulders", equipment: "Cable", level: "Beginner", emoji: "\ud83e\udea2", movement: "Isolation", sport: "Gym", muscles: ["Side delts"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g66", name: "Front raise", group: "Shoulders", equipment: "Dumbbell", level: "Beginner", emoji: "\u2b06\ufe0f", movement: "Isolation", sport: "Gym", muscles: ["Front delts"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g67", name: "Reverse pec deck", group: "Shoulders", equipment: "Machine", level: "Beginner", emoji: "\u2699\ufe0f", movement: "Isolation", sport: "Gym", muscles: ["Rear delts"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g68", name: "Bent-over rear delt raise", group: "Shoulders", equipment: "Dumbbell", level: "Beginner", emoji: "\ud83e\udd85", movement: "Isolation", sport: "Gym", muscles: ["Rear delts"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g69", name: "Upright row", group: "Shoulders", equipment: "Barbell", level: "Intermediate", emoji: "\u2b06\ufe0f", movement: "Pull", sport: "Gym", muscles: ["Side delts", "Traps"], cues: ["Lead with the elbows", "Pause briefly at the top", "Lower under control"], sets: "3-4", reps: "8-12", rest: 90 },
  { id: "g70", name: "Landmine press", group: "Shoulders", equipment: "Barbell", level: "Intermediate", emoji: "\ud83d\udccc", movement: "Push", sport: "Gym", muscles: ["Shoulders", "Chest"], cues: ["Set the shoulder blades first", "Elbows tucked around 45\u00b0", "Control the lowering phase"], sets: "3-4", reps: "6-12", rest: 90 },
  { id: "g71", name: "Pike push-up", group: "Shoulders", equipment: "Bodyweight", level: "Intermediate", emoji: "\ud83d\udd3a", movement: "Push", sport: "Gym", muscles: ["Shoulders"], cues: ["Set the shoulder blades first", "Elbows tucked around 45\u00b0", "Control the lowering phase"], sets: "3-4", reps: "6-12", rest: 90 },
  { id: "g72", name: "Barbell curl", group: "Arms", equipment: "Barbell", level: "Beginner", emoji: "\ud83d\udcaa", movement: "Isolation", sport: "Gym", muscles: ["Biceps"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g73", name: "Dumbbell curl", group: "Arms", equipment: "Dumbbell", level: "Beginner", emoji: "\ud83d\udcaa", movement: "Isolation", sport: "Gym", muscles: ["Biceps"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g74", name: "Hammer curl", group: "Arms", equipment: "Dumbbell", level: "Beginner", emoji: "\ud83d\udd28", movement: "Isolation", sport: "Gym", muscles: ["Biceps", "Forearms"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g75", name: "Incline dumbbell curl", group: "Arms", equipment: "Dumbbell", level: "Intermediate", emoji: "\ud83d\udcd0", movement: "Isolation", sport: "Gym", muscles: ["Biceps"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g76", name: "Preacher curl", group: "Arms", equipment: "Barbell", level: "Intermediate", emoji: "\ud83d\ude4f", movement: "Isolation", sport: "Gym", muscles: ["Biceps"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g77", name: "Cable curl", group: "Arms", equipment: "Cable", level: "Beginner", emoji: "\ud83e\udea2", movement: "Isolation", sport: "Gym", muscles: ["Biceps"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g78", name: "Concentration curl", group: "Arms", equipment: "Dumbbell", level: "Beginner", emoji: "\ud83c\udfaf", movement: "Isolation", sport: "Gym", muscles: ["Biceps"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g79", name: "Reverse curl", group: "Arms", equipment: "Barbell", level: "Beginner", emoji: "\ud83d\udd04", movement: "Isolation", sport: "Gym", muscles: ["Forearms", "Biceps"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g80", name: "Triceps rope pushdown", group: "Arms", equipment: "Cable", level: "Beginner", emoji: "\ud83e\udea2", movement: "Isolation", sport: "Gym", muscles: ["Triceps"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g81", name: "Overhead cable triceps extension", group: "Arms", equipment: "Cable", level: "Intermediate", emoji: "\ud83e\udea2", movement: "Isolation", sport: "Gym", muscles: ["Triceps"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g82", name: "Skull crusher", group: "Arms", equipment: "Barbell", level: "Intermediate", emoji: "\ud83d\udc80", movement: "Isolation", sport: "Gym", muscles: ["Triceps"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g83", name: "Triceps dip", group: "Arms", equipment: "Bodyweight", level: "Beginner", emoji: "\ud83e\ude91", movement: "Push", sport: "Gym", muscles: ["Triceps"], cues: ["Set the shoulder blades first", "Elbows tucked around 45\u00b0", "Control the lowering phase"], sets: "3-4", reps: "6-12", rest: 90 },
  { id: "g84", name: "Dumbbell kickback", group: "Arms", equipment: "Dumbbell", level: "Beginner", emoji: "\ud83e\uddb5", movement: "Isolation", sport: "Gym", muscles: ["Triceps"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g85", name: "Wrist curl", group: "Arms", equipment: "Dumbbell", level: "Beginner", emoji: "\ud83e\udd32", movement: "Isolation", sport: "Gym", muscles: ["Forearms"], cues: ["Slow and controlled tempo", "Full range, no swinging", "Feel the target muscle working"], sets: "3", reps: "10-15", rest: 60 },
  { id: "g86", name: "Farmer's carry", group: "Full body", equipment: "Dumbbell", level: "Beginner", emoji: "\ud83e\uddf3", movement: "Carry", sport: "Gym", muscles: ["Grip", "Core", "Traps"], cues: ["Stand tall, shoulders back", "Squeeze the handle hard", "Slow, even steps"], sets: "3", reps: "30-40 m", rest: 75 },
  { id: "g87", name: "Suitcase carry", group: "Full body", equipment: "Kettlebell", level: "Beginner", emoji: "\ud83e\uddf3", movement: "Carry", sport: "Gym", muscles: ["Core", "Grip"], cues: ["Stand tall, shoulders back", "Squeeze the handle hard", "Slow, even steps"], sets: "3", reps: "30-40 m", rest: 75 },
  { id: "g88", name: "Sled push", group: "Full body", equipment: "Machine", level: "Intermediate", emoji: "\ud83d\udef7", movement: "Cardio", sport: "Gym", muscles: ["Legs", "Core"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "g89", name: "Battle ropes", group: "Full body", equipment: "Machine", level: "Intermediate", emoji: "\ud83e\udea2", movement: "Cardio", sport: "Gym", muscles: ["Shoulders", "Core"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "g90", name: "Thruster", group: "Full body", equipment: "Barbell", level: "Advanced", emoji: "\ud83d\ude80", movement: "Push", sport: "Gym", muscles: ["Legs", "Shoulders"], cues: ["Set the shoulder blades first", "Elbows tucked around 45\u00b0", "Control the lowering phase"], sets: "3-4", reps: "6-12", rest: 90 },
  { id: "g91", name: "Clean and press", group: "Full body", equipment: "Barbell", level: "Advanced", emoji: "\ud83c\udfc5", movement: "Olympic", sport: "Gym", muscles: ["Full body"], cues: ["Bar close to the body", "Extend the hips fully", "Catch with the elbows fast"], sets: "5", reps: "3", rest: 150 },
  { id: "g92", name: "Power clean", group: "Full body", equipment: "Barbell", level: "Advanced", emoji: "\ud83c\udfc5", movement: "Olympic", sport: "Gym", muscles: ["Legs", "Back"], cues: ["Bar close to the body", "Extend the hips fully", "Catch with the elbows fast"], sets: "5", reps: "3", rest: 150 },
  { id: "g93", name: "Hang snatch", group: "Full body", equipment: "Barbell", level: "Advanced", emoji: "\ud83c\udfc5", movement: "Olympic", sport: "Gym", muscles: ["Full body"], cues: ["Bar close to the body", "Extend the hips fully", "Catch with the elbows fast"], sets: "5", reps: "3", rest: 150 },
  { id: "g94", name: "Kettlebell clean", group: "Full body", equipment: "Kettlebell", level: "Intermediate", emoji: "\ud83d\udd14", movement: "Olympic", sport: "Gym", muscles: ["Legs", "Back"], cues: ["Bar close to the body", "Extend the hips fully", "Catch with the elbows fast"], sets: "5", reps: "3", rest: 150 },
  { id: "g95", name: "Turkish get-up", group: "Full body", equipment: "Kettlebell", level: "Advanced", emoji: "\ud83d\udd14", movement: "Core", sport: "Gym", muscles: ["Core", "Shoulders"], cues: ["Ribs stacked over hips", "Breathe steadily throughout", "Quality over reps"], sets: "3", reps: "30-45 sec", rest: 45 },
  { id: "g96", name: "Medicine ball slam", group: "Full body", equipment: "Machine", level: "Beginner", emoji: "\ud83c\udfd0", movement: "Plyometric", sport: "Gym", muscles: ["Core", "Shoulders"], cues: ["Land softly through the whole foot", "Reset fully between reps", "Quality jumps beat tired jumps"], sets: "4", reps: "3-5", rest: 90 },
  { id: "g97", name: "Box jump", group: "Full body", equipment: "Bodyweight", level: "Intermediate", emoji: "\ud83d\udce6", movement: "Plyometric", sport: "Gym", muscles: ["Legs"], cues: ["Land softly through the whole foot", "Reset fully between reps", "Quality jumps beat tired jumps"], sets: "4", reps: "3-5", rest: 90 },
  { id: "g98", name: "Broad jump", group: "Full body", equipment: "Bodyweight", level: "Intermediate", emoji: "\ud83e\udd98", movement: "Plyometric", sport: "Gym", muscles: ["Legs"], cues: ["Land softly through the whole foot", "Reset fully between reps", "Quality jumps beat tired jumps"], sets: "4", reps: "3-5", rest: 90 },
  { id: "g99", name: "Jump squat", group: "Full body", equipment: "Bodyweight", level: "Intermediate", emoji: "\ud83e\udd98", movement: "Plyometric", sport: "Gym", muscles: ["Legs"], cues: ["Land softly through the whole foot", "Reset fully between reps", "Quality jumps beat tired jumps"], sets: "4", reps: "3-5", rest: 90 },
  { id: "g100", name: "Dead bug", group: "Core", equipment: "Bodyweight", level: "Beginner", emoji: "\ud83d\udc1e", movement: "Core", sport: "Gym", muscles: ["Deep core"], cues: ["Ribs stacked over hips", "Breathe steadily throughout", "Quality over reps"], sets: "3", reps: "30-45 sec", rest: 45 },
  { id: "g101", name: "Hollow hold", group: "Core", equipment: "Bodyweight", level: "Intermediate", emoji: "\ud83c\udf19", movement: "Core", sport: "Gym", muscles: ["Deep core"], cues: ["Ribs stacked over hips", "Breathe steadily throughout", "Quality over reps"], sets: "3", reps: "30-45 sec", rest: 45 },
  { id: "g102", name: "Side plank", group: "Core", equipment: "Bodyweight", level: "Beginner", emoji: "\ud83d\udccf", movement: "Core", sport: "Gym", muscles: ["Obliques"], cues: ["Ribs stacked over hips", "Breathe steadily throughout", "Quality over reps"], sets: "3", reps: "30-45 sec", rest: 45 },
  { id: "g103", name: "Cable woodchop", group: "Core", equipment: "Cable", level: "Intermediate", emoji: "\ud83e\ude93", movement: "Rotation", sport: "Gym", muscles: ["Obliques"], cues: ["Move from the ribcage", "Hips stay square", "Resist the pull, don't yank"], sets: "3", reps: "10-12 / side", rest: 45 },
  { id: "g104", name: "Pallof press", group: "Core", equipment: "Cable", level: "Beginner", emoji: "\ud83e\udea2", movement: "Rotation", sport: "Gym", muscles: ["Deep core"], cues: ["Move from the ribcage", "Hips stay square", "Resist the pull, don't yank"], sets: "3", reps: "10-12 / side", rest: 45 },
  { id: "g105", name: "Russian twist", group: "Core", equipment: "Bodyweight", level: "Beginner", emoji: "\ud83c\udf00", movement: "Rotation", sport: "Gym", muscles: ["Obliques"], cues: ["Move from the ribcage", "Hips stay square", "Resist the pull, don't yank"], sets: "3", reps: "10-12 / side", rest: 45 },
  { id: "g106", name: "Cable crunch", group: "Core", equipment: "Cable", level: "Beginner", emoji: "\ud83e\udea2", movement: "Core", sport: "Gym", muscles: ["Abs"], cues: ["Ribs stacked over hips", "Breathe steadily throughout", "Quality over reps"], sets: "3", reps: "30-45 sec", rest: 45 },
  { id: "g107", name: "Toes to bar", group: "Core", equipment: "Pull-up bar", level: "Advanced", emoji: "\ud83e\ude9d", movement: "Core", sport: "Gym", muscles: ["Abs"], cues: ["Ribs stacked over hips", "Breathe steadily throughout", "Quality over reps"], sets: "3", reps: "30-45 sec", rest: 45 },
  { id: "g108", name: "Ab wheel rollout", group: "Core", equipment: "Machine", level: "Advanced", emoji: "\ud83c\udfa1", movement: "Core", sport: "Gym", muscles: ["Abs", "Deep core"], cues: ["Ribs stacked over hips", "Breathe steadily throughout", "Quality over reps"], sets: "3", reps: "30-45 sec", rest: 45 },
  { id: "g109", name: "Reverse crunch", group: "Core", equipment: "Bodyweight", level: "Beginner", emoji: "\ud83d\udd04", movement: "Core", sport: "Gym", muscles: ["Abs"], cues: ["Ribs stacked over hips", "Breathe steadily throughout", "Quality over reps"], sets: "3", reps: "30-45 sec", rest: 45 },
  { id: "g110", name: "Treadmill intervals", group: "Cardio", equipment: "Machine", level: "Intermediate", emoji: "\ud83c\udfc3", movement: "Cardio", sport: "Gym", muscles: ["Heart", "Legs"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "g111", name: "Incline treadmill walk", group: "Cardio", equipment: "Machine", level: "Beginner", emoji: "\u26f0\ufe0f", movement: "Cardio", sport: "Gym", muscles: ["Heart", "Calves"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "g112", name: "Stationary bike intervals", group: "Cardio", equipment: "Machine", level: "Beginner", emoji: "\ud83d\udeb4", movement: "Cardio", sport: "Gym", muscles: ["Heart", "Quads"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "g113", name: "Stair climber", group: "Cardio", equipment: "Machine", level: "Beginner", emoji: "\ud83e\ude9c", movement: "Cardio", sport: "Gym", muscles: ["Heart", "Glutes"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "g114", name: "Elliptical steady state", group: "Cardio", equipment: "Machine", level: "Beginner", emoji: "\u2699\ufe0f", movement: "Cardio", sport: "Gym", muscles: ["Heart"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "g115", name: "Ski erg intervals", group: "Cardio", equipment: "Machine", level: "Intermediate", emoji: "\ud83c\udfbf", movement: "Cardio", sport: "Gym", muscles: ["Heart", "Lats"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "g116", name: "Assault bike sprints", group: "Cardio", equipment: "Machine", level: "Advanced", emoji: "\ud83d\udeb2", movement: "Cardio", sport: "Gym", muscles: ["Heart", "Full body"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "g117", name: "Jump rope", group: "Cardio", equipment: "Bodyweight", level: "Beginner", emoji: "\ud83e\udea2", movement: "Cardio", sport: "Gym", muscles: ["Calves", "Heart"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "g118", name: "High knees", group: "Cardio", equipment: "Bodyweight", level: "Beginner", emoji: "\ud83e\uddb5", movement: "Cardio", sport: "Gym", muscles: ["Hip flexors", "Heart"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "g119", name: "Shadow skipping drill", group: "Cardio", equipment: "Bodyweight", level: "Beginner", emoji: "\ud83d\udc5f", movement: "Cardio", sport: "Gym", muscles: ["Calves"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "g120", name: "World's greatest stretch", group: "Mobility", equipment: "Bodyweight", level: "Beginner", emoji: "\ud83c\udf0d", movement: "Mobility", sport: "Gym", muscles: ["Hips", "Thoracic"], cues: ["Ease into the range, never force", "Breathe out to sink deeper", "Hold 30-45 seconds per side"], sets: "2", reps: "30-45 sec", rest: 30 },
  { id: "g121", name: "Thoracic rotation", group: "Mobility", equipment: "Bodyweight", level: "Beginner", emoji: "\ud83c\udf00", movement: "Mobility", sport: "Gym", muscles: ["Thoracic"], cues: ["Ease into the range, never force", "Breathe out to sink deeper", "Hold 30-45 seconds per side"], sets: "2", reps: "30-45 sec", rest: 30 },
  { id: "g122", name: "90/90 hip switch", group: "Mobility", equipment: "Bodyweight", level: "Beginner", emoji: "\ud83e\uddb5", movement: "Mobility", sport: "Gym", muscles: ["Hips"], cues: ["Ease into the range, never force", "Breathe out to sink deeper", "Hold 30-45 seconds per side"], sets: "2", reps: "30-45 sec", rest: 30 },
  { id: "g123", name: "Couch stretch", group: "Mobility", equipment: "Bodyweight", level: "Intermediate", emoji: "\ud83d\udecb\ufe0f", movement: "Mobility", sport: "Gym", muscles: ["Hip flexors"], cues: ["Ease into the range, never force", "Breathe out to sink deeper", "Hold 30-45 seconds per side"], sets: "2", reps: "30-45 sec", rest: 30 },
  { id: "g124", name: "Band shoulder dislocate", group: "Mobility", equipment: "Cable", level: "Beginner", emoji: "\ud83c\udf97\ufe0f", movement: "Mobility", sport: "Gym", muscles: ["Shoulders"], cues: ["Ease into the range, never force", "Breathe out to sink deeper", "Hold 30-45 seconds per side"], sets: "2", reps: "30-45 sec", rest: 30 },
  { id: "g125", name: "Ankle rocker", group: "Mobility", equipment: "Bodyweight", level: "Beginner", emoji: "\ud83e\uddb6", movement: "Mobility", sport: "Gym", muscles: ["Ankles"], cues: ["Ease into the range, never force", "Breathe out to sink deeper", "Hold 30-45 seconds per side"], sets: "2", reps: "30-45 sec", rest: 30 },
  { id: "s1", name: "Tempo run", group: "Running", equipment: "Bodyweight", level: "Intermediate", emoji: "\ud83c\udfc3", movement: "Cardio", sport: "Running", muscles: ["Heart", "Legs"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "s2", name: "Easy zone-2 run", group: "Running", equipment: "Bodyweight", level: "Beginner", emoji: "\ud83c\udfc3", movement: "Cardio", sport: "Running", muscles: ["Heart"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "s3", name: "Hill repeats", group: "Running", equipment: "Bodyweight", level: "Advanced", emoji: "\u26f0\ufe0f", movement: "Cardio", sport: "Running", muscles: ["Glutes", "Heart"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "s4", name: "Track 400m repeats", group: "Running", equipment: "Bodyweight", level: "Advanced", emoji: "\ud83c\udfdf\ufe0f", movement: "Cardio", sport: "Running", muscles: ["Heart", "Legs"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "s5", name: "Strides", group: "Running", equipment: "Bodyweight", level: "Beginner", emoji: "\ud83d\udc5f", movement: "Cardio", sport: "Running", muscles: ["Legs"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "s6", name: "Freestyle swim set", group: "Swimming", equipment: "Bodyweight", level: "Intermediate", emoji: "\ud83c\udfca", movement: "Cardio", sport: "Swimming", muscles: ["Lats", "Heart"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "s7", name: "Kick board drill", group: "Swimming", equipment: "Bodyweight", level: "Beginner", emoji: "\ud83c\udfca", movement: "Cardio", sport: "Swimming", muscles: ["Quads", "Core"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "s8", name: "Pull buoy drill", group: "Swimming", equipment: "Bodyweight", level: "Intermediate", emoji: "\ud83c\udfca", movement: "Cardio", sport: "Swimming", muscles: ["Lats", "Shoulders"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "s9", name: "Road cycling endurance ride", group: "Cycling", equipment: "Bodyweight", level: "Beginner", emoji: "\ud83d\udeb4", movement: "Cardio", sport: "Cycling", muscles: ["Quads", "Heart"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "s10", name: "Cycling hill intervals", group: "Cycling", equipment: "Bodyweight", level: "Advanced", emoji: "\ud83d\udeb5", movement: "Cardio", sport: "Cycling", muscles: ["Quads", "Heart"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "s11", name: "Cadence drill", group: "Cycling", equipment: "Bodyweight", level: "Beginner", emoji: "\ud83d\udeb4", movement: "Cardio", sport: "Cycling", muscles: ["Quads"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "s12", name: "Football shuttle runs", group: "Football", equipment: "Bodyweight", level: "Intermediate", emoji: "\u26bd", movement: "Cardio", sport: "Football", muscles: ["Legs", "Heart"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "s13", name: "Dribbling cone drill", group: "Football", equipment: "Bodyweight", level: "Beginner", emoji: "\u26bd", movement: "Cardio", sport: "Football", muscles: ["Calves", "Coordination"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "s14", name: "Shooting practice", group: "Football", equipment: "Bodyweight", level: "Beginner", emoji: "\u26bd", movement: "Cardio", sport: "Football", muscles: ["Hips", "Core"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "s15", name: "Basketball defensive slides", group: "Basketball", equipment: "Bodyweight", level: "Intermediate", emoji: "\ud83c\udfc0", movement: "Cardio", sport: "Basketball", muscles: ["Glutes", "Quads"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "s16", name: "Layup drill", group: "Basketball", equipment: "Bodyweight", level: "Beginner", emoji: "\ud83c\udfc0", movement: "Cardio", sport: "Basketball", muscles: ["Legs", "Coordination"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "s17", name: "Free-throw routine", group: "Basketball", equipment: "Bodyweight", level: "Beginner", emoji: "\ud83c\udfc0", movement: "Cardio", sport: "Basketball", muscles: ["Shoulders"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "s18", name: "Tennis serve practice", group: "Tennis", equipment: "Bodyweight", level: "Intermediate", emoji: "\ud83c\udfbe", movement: "Cardio", sport: "Tennis", muscles: ["Shoulders", "Core"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "s19", name: "Tennis ladder footwork", group: "Tennis", equipment: "Bodyweight", level: "Beginner", emoji: "\ud83c\udfbe", movement: "Cardio", sport: "Tennis", muscles: ["Calves"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "s20", name: "Boxing shadow rounds", group: "Boxing", equipment: "Bodyweight", level: "Beginner", emoji: "\ud83e\udd4a", movement: "Cardio", sport: "Boxing", muscles: ["Shoulders", "Core"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "s21", name: "Heavy bag intervals", group: "Boxing", equipment: "Machine", level: "Intermediate", emoji: "\ud83e\udd4a", movement: "Cardio", sport: "Boxing", muscles: ["Shoulders", "Heart"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "s22", name: "Jump rope footwork rounds", group: "Boxing", equipment: "Bodyweight", level: "Intermediate", emoji: "\ud83e\udea2", movement: "Cardio", sport: "Boxing", muscles: ["Calves"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
  { id: "s23", name: "Sun salutation flow", group: "Yoga", equipment: "Bodyweight", level: "Beginner", emoji: "\ud83e\uddd8", movement: "Mobility", sport: "Yoga", muscles: ["Full body"], cues: ["Ease into the range, never force", "Breathe out to sink deeper", "Hold 30-45 seconds per side"], sets: "2", reps: "30-45 sec", rest: 30 },
  { id: "s24", name: "Warrior sequence", group: "Yoga", equipment: "Bodyweight", level: "Beginner", emoji: "\ud83e\uddd8", movement: "Mobility", sport: "Yoga", muscles: ["Legs", "Hips"], cues: ["Ease into the range, never force", "Breathe out to sink deeper", "Hold 30-45 seconds per side"], sets: "2", reps: "30-45 sec", rest: 30 },
  { id: "s25", name: "Yoga balance holds", group: "Yoga", equipment: "Bodyweight", level: "Intermediate", emoji: "\ud83e\uddd8", movement: "Mobility", sport: "Yoga", muscles: ["Ankles", "Core"], cues: ["Ease into the range, never force", "Breathe out to sink deeper", "Hold 30-45 seconds per side"], sets: "2", reps: "30-45 sec", rest: 30 },
  { id: "s26", name: "Pilates hundred", group: "Pilates", equipment: "Bodyweight", level: "Beginner", emoji: "\ud83e\udd38", movement: "Core", sport: "Pilates", muscles: ["Deep core"], cues: ["Ribs stacked over hips", "Breathe steadily throughout", "Quality over reps"], sets: "3", reps: "30-45 sec", rest: 45 },
  { id: "s27", name: "Pilates leg circles", group: "Pilates", equipment: "Bodyweight", level: "Beginner", emoji: "\ud83e\udd38", movement: "Core", sport: "Pilates", muscles: ["Hips", "Core"], cues: ["Ribs stacked over hips", "Breathe steadily throughout", "Quality over reps"], sets: "3", reps: "30-45 sec", rest: 45 },
  { id: "s28", name: "Climbing hangboard repeaters", group: "Climbing", equipment: "Pull-up bar", level: "Advanced", emoji: "\ud83e\uddd7", movement: "Core", sport: "Climbing", muscles: ["Forearms", "Lats"], cues: ["Ribs stacked over hips", "Breathe steadily throughout", "Quality over reps"], sets: "3", reps: "30-45 sec", rest: 45 },
  { id: "s29", name: "Bouldering circuits", group: "Climbing", equipment: "Bodyweight", level: "Intermediate", emoji: "\ud83e\uddd7", movement: "Core", sport: "Climbing", muscles: ["Back", "Grip"], cues: ["Ribs stacked over hips", "Breathe steadily throughout", "Quality over reps"], sets: "3", reps: "30-45 sec", rest: 45 },
  { id: "s30", name: "Rowing 2k test", group: "Rowing", equipment: "Machine", level: "Advanced", emoji: "\ud83d\udea3", movement: "Cardio", sport: "Rowing", muscles: ["Full body", "Heart"], cues: ["Start easy and build", "Relaxed shoulders, steady breathing", "Finish stronger than you started"], sets: "1-5", reps: "intervals", rest: 60 },
];

export const LIBRARY: LibraryExercise[] = [...CORE_LIBRARY, ...EXTRA_LIBRARY];

export const GYM_COUNT = LIBRARY.filter((e) => e.sport === "Gym").length;
export const SPORT_COUNT = LIBRARY.length - GYM_COUNT;

export const MUSCLE_GROUPS = ["All", ...new Set(LIBRARY.map((e) => e.group))];
export const EQUIPMENT = ["All", ...new Set(LIBRARY.map((e) => e.equipment))];
export const LEVELS = ["All", "Beginner", "Intermediate", "Advanced"] as const;
export const MOVEMENTS = ["All", ...new Set(LIBRARY.map((e) => e.movement))];
export const SPORTS = ["All", ...new Set(LIBRARY.map((e) => e.sport))];

export function findExercise(id: string): LibraryExercise | undefined {
  return LIBRARY.find((e) => e.id === id);
}